/*
# Seed welfare schemes catalog

## Overview
Populates the schemes table with a curated catalog of representative government
welfare programs across categories. Adds a unique constraint on schemes.title
to make the seed idempotent via ON CONFLICT (title) DO NOTHING.

## Security
No security changes.

## Notes
1. Idempotent: unique constraint on title + ON CONFLICT DO NOTHING.
*/

CREATE UNIQUE INDEX IF NOT EXISTS schemes_title_unique ON schemes(title);

INSERT INTO schemes (title, category, description, eligibility, benefit_amount, benefit_unit, eligibility_criteria, documents_required, application_url, contact_info)
VALUES
  ('National Health Insurance', 'healthcare', 'A government-backed health insurance program providing cashless hospitalization coverage to eligible families, covering hospitalization expenses, surgeries, and critical illness treatment at empaneled hospitals nationwide.', 'Low-income families with no formal health coverage', 500000, 'per year coverage', ARRAY['Annual family income below poverty line threshold','No existing private health insurance','Valid national identity document','Domicile of participating region'], ARRAY['Identity proof (national ID card)','Income certificate','Domicile certificate','Family roster document','Bank account details'], NULL, 'Toll-free: 1800-XXX-XXXX | Email: healthscheme@gov.example'),
  ('Maternity Benefit Program', 'women', 'A financial assistance program for pregnant and nursing mothers providing cash benefits to support nutrition and healthcare during pregnancy and after childbirth, reducing maternal and infant mortality.', 'Pregnant and nursing mothers from low-income households', 6000, 'one-time per pregnancy', ARRAY['Pregnant or nursing mother','Age 19 years or above','First two living children','Registered at an authorized health center'], ARRAY['Mother identity proof','Mother-and-child protection card','Bank account in mother name','Income certificate','Husband identity proof'], NULL, 'Toll-free: 1800-XXX-XXXX'),
  ('Public Distribution Food Security', 'food', 'A subsidized food grain distribution system providing essential food items at highly subsidized rates to eligible households through a network of fair-price shops, ensuring nutritional security.', 'Households meeting income and vulnerability criteria', NULL, 'monthly food grains', ARRAY['Household income below defined threshold','Valid ration card category','Domicile of the state','No member in regular government employment'], ARRAY['Ration card application','Identity proof of head of household','Address proof','Income certificate','Family members list'], NULL, 'Toll-free: 1967'),
  ('Affordable Housing for All', 'housing', 'A housing assistance program providing interest subsidies on home loans and grant components for construction of pucca houses to eligible families without permanent shelter.', 'Economically weaker and low-income groups without pucca housing', 250000, 'grant + interest subsidy', ARRAY['No pucca house in family name','Annual household income within EWS/LIG band','No prior central housing benefit availed','Domicile of the state'], ARRAY['Identity proof','Income certificate','Domicile certificate','Land ownership or allotment document','Bank account details'], NULL, 'Email: housingmission@gov.example'),
  ('Rural Employment Guarantee', 'employment', 'A legally guaranteed wage employment program providing at least 100 days of unskilled manual work per financial year to rural households, with unemployment allowance if work is not provided.', 'Rural households seeking unskilled employment', NULL, '100 days per year wages', ARRAY['Rural household','Adult members willing to do unskilled manual work','Local job card registration','Application with photo and identity'], ARRAY['Household job card','Photographs of adult members','Identity proof','Bank or post office account','Residence proof'], NULL, 'Toll-free: 1800-XXX-XXXX'),
  ('Primary Education Access', 'education', 'A free and compulsory education program ensuring admission to age-appropriate classes for children aged 6-14, with free textbooks, midday meals, and no capitation fees.', 'Children aged 6 to 14 years', NULL, 'free schooling', ARRAY['Child aged 6-14 years','Belongs to disadvantaged group or below income threshold','No prior private school enrollment under quota','Resident of the school catchment area'], ARRAY['Child birth certificate','Parent identity proof','Address proof','Income or caste certificate where applicable','School transfer certificate if any'], NULL, 'Toll-free: 1800-XXX-XXXX'),
  ('Higher Education Scholarship', 'education', 'A merit-cum-means scholarship providing full tuition fee reimbursement and a maintenance allowance to economically backward students pursuing professional and technical higher education.', 'Students from minority and low-income communities in higher education', 20000, 'per academic year', ARRAY['Enrolled in a recognized professional/technical course','Family income below threshold','Minimum 50% marks in previous examination','Valid minority community certificate where applicable'], ARRAY['Marksheet of last qualifying exam','Income certificate','Community certificate','Admission proof / fee receipt','Bank account in student name'], NULL, 'Email: scholarships@gov.example'),
  ('Senior Citizen Pension', 'senior', 'A monthly pension scheme providing financial support to elderly citizens belonging to below-poverty-line households, ensuring dignified living and basic needs coverage.', 'Senior citizens aged 60+ from BPL households', 1000, 'per month', ARRAY['Age 60 years or above','Belongs to below-poverty-line category','No other government pension availed','Domicile of the state'], ARRAY['Age proof (birth certificate or school certificate)','Identity proof','BPL / income certificate','Domicile certificate','Bank account details'], NULL, 'Toll-free: 1800-XXX-XXXX'),
  ('Disability Support Allowance', 'disability', 'A financial assistance program providing a monthly allowance and skill development support to persons with benchmark disabilities, promoting independent living and equal participation.', 'Persons with 40% or more certified disability', 1500, 'per month', ARRAY['Certified disability of 40% or more','Age 18 years or above','Family income below defined threshold','Valid disability certificate from medical board'], ARRAY['Disability certificate from medical board','Identity proof','Income certificate','Address proof','Bank account in applicant name'], NULL, 'Email: disabilityaffairs@gov.example'),
  ('Crop Insurance Scheme', 'agriculture', 'A crop insurance program protecting farmers against crop loss due to natural calamities, pests, and diseases, with low premium rates and prompt claim settlement based on yield data.', 'Farmer households cultivating notified crops', NULL, 'crop loss coverage', ARRAY['Active farmer cultivating notified crops in notified area','Land ownership or tenant cultivation proof','Loan account with bank if loanee farmer','Application within notified season window'], ARRAY['Land records / patta','Sowing certificate from local agriculture officer','Identity proof','Bank account / loan account details','Crop and area details'], NULL, 'Toll-free: 1800-XXX-XXXX'),
  ('Women Self-Help Group Loan', 'women', 'A credit-linked subsidy scheme enabling women self-help groups in rural areas to access collateral-free bank loans for income-generating activities at subsidized interest rates.', 'Rural women self-help groups (SHGs) aged 18+', 300000, 'subsidized loan limit', ARRAY['Women-only SHG of 10-20 members','Members aged 18 years or above','Group savings active for minimum 6 months','Resident of rural area'], ARRAY['SHG registration certificate','Member identity proofs','Group savings record / bank statement','Resolution to avail loan','Proposed activity plan'], NULL, 'Email: rural-credit@gov.example'),
  ('Direct Cash Transfer', 'financial', 'A direct benefit transfer program delivering cash subsidies and welfare payments straight into beneficiary bank accounts, reducing leakage and ensuring timely disbursement of entitled amounts.', 'Eligible beneficiaries of notified welfare schemes with bank accounts', 0, 'varies by scheme', ARRAY['Listed beneficiary under a notified scheme','Active bank account linked to national ID','Aadhaar / national ID seeding complete','Mobile number linked for OTP verification'], ARRAY['National identity card','Bank passbook','Mobile number proof','Scheme-specific eligibility certificate'], NULL, 'Toll-free: 1947'),
  ('Skill Development Training', 'employment', 'A short-duration skill training program offering industry-relevant training, certification, and placement support to unemployed youth, with a stipend during training.', 'Unemployed youth and young adults aged 15-45', 8000, 'one-time stipend', ARRAY['Age 15-45 years','Unemployed or underemployed','Educational qualification per course requirement','Valid identity and address proof'], ARRAY['Identity proof','Address proof','Educational certificates','Bank account details','Recent passport-size photograph'], NULL, 'Email: skillmission@gov.example'),
  ('Farm Loan Waiver', 'agriculture', 'A targeted debt relief program waiving outstanding crop loans of marginal and small farmers, restoring their creditworthiness and enabling fresh agricultural borrowing.', 'Marginal and small farmers with outstanding crop loans', 100000, 'one-time waiver', ARRAY['Marginal or small farmer (holding up to 2 hectares)','Outstanding crop loan from scheduled bank','Loan account standard as on notified cutoff date','Domicile of participating state'], ARRAY['Land records / patta','Bank loan account statement','Identity proof','Domicile certificate','Crop loan sanction letter'], NULL, 'Toll-free: 1800-XXX-XXXX'),
  ('Widow Pension Scheme', 'women', 'A monthly pension providing financial security to widowed women from low-income groups, with additional support for dependent children and skill training for self-employment.', 'Widowed women aged 18+ from BPL households', 500, 'per month', ARRAY['Widowed woman aged 18 years or above','Family income below poverty line','No remarriage','Domicile of the state'], ARRAY['Death certificate of husband','Identity proof','Income or BPL certificate','Domicile certificate','Bank account in applicant name'], NULL, 'Toll-free: 1800-XXX-XXXX')
ON CONFLICT (title) DO NOTHING;
